sigungu_code: "lawd_cd"
contract_year_month: "deal_ym"
legal_dong: "umdNm"
housing_type: "houseType"
rental_area: "totalFloorAr"
built_year: "buildYear"
deposit: "deposit"
monthly_rent: "monthlyRent"
contract_term: "contractTerm"
contract_type: "contractType"
renewal_right_used: "useRRRight"
